artifact_uri: /Users/rahulsiddharthdacha/Desktop/BITS/mid_sem/mlflow/282570187416666551/3e09cad6bd864b77a1ff4519749c216f/artifacts
end_time: 1767243424691
entry_point_name: ''
experiment_id: '282570187416666551'
lifecycle_stage: active
run_id: 3e09cad6bd864b77a1ff4519749c216f
run_name: RandomForest
source_name: ''
source_type: 4
source_version: ''
start_time: 1767243422519
status: 3
tags: []
user_id: rahulsiddharthdacha
