artifact_location: /Users/rahulsiddharthdacha/Desktop/BITS/mid_sem/mlflow/282570187416666551
creation_time: 1767243421033
experiment_id: '282570187416666551'
last_update_time: 1767243421033
lifecycle_stage: active
name: excel_table_detection_model_comparison
