artifact_uri: /Users/rahulsiddharthdacha/Desktop/BITS/mid_sem/mlflow/282570187416666551/7483daa9f3aa49b9904b40ef7fc4fc12/artifacts
end_time: 1767243434762
entry_point_name: ''
experiment_id: '282570187416666551'
lifecycle_stage: active
run_id: 7483daa9f3aa49b9904b40ef7fc4fc12
run_name: SVM
source_name: ''
source_type: 4
source_version: ''
start_time: 1767243433386
status: 3
tags: []
user_id: rahulsiddharthdacha
