artifact_location: /Users/rahulsiddharthdacha/Desktop/BITS/mid_sem/mlflows/126946449638471464
creation_time: 1767216495444
experiment_id: '126946449638471464'
last_update_time: 1767216495444
lifecycle_stage: active
name: excel_table_detection_model_comparison
