artifact_uri: /Users/rahulsiddharthdacha/Desktop/BITS/mid_sem/mlflow/282570187416666551/3f718a3ef55e4b84b80c285a8ff3e653/artifacts
end_time: 1767243433385
entry_point_name: ''
experiment_id: '282570187416666551'
lifecycle_stage: active
run_id: 3f718a3ef55e4b84b80c285a8ff3e653
run_name: GradientBoosting
source_name: ''
source_type: 4
source_version: ''
start_time: 1767243424692
status: 3
tags: []
user_id: rahulsiddharthdacha
